### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by Baroshem** [nuxt-community/algolia-module#21]
### What is actually happening?

* [Coming soon] for VueInstantsearch -> coming soon should be removed as there is already a support for that both README.md and docs
* Update vue-instantsearch usage docs to have // path/to/file in the code examples and also we should add better guide on how to use it. More descriptive.

**Comment by Atinux** [comment]
Would be nice to also document the usage of the `publicRuntimeConfig` with the `.env` 😄

**Comment by Baroshem** [comment]
Sure @Atinux let's add this as well! ❤️
