### ISSUE TITLE
Query with attributes

### ISSUE THREAD

**Issue by andyjamesn** [nuxt-community/algolia-module#31]
Reading the documentation it shows a search can be done as follows:

`await search({ query: 'Samsung' });`

This is working as expected but I am having some trouble trying to get the intended format for passing parameters with the query. As per the Algolia documentation this is the format

```
index.search('query string', {
  attributesToRetrieve: ['firstname', 'lastname'],
  hitsPerPage: 50,
})

```

Looking at the useSearch composable

https://github.com/nuxt-community/algolia-module/blob/main/src/runtime/composables/useSearch.ts

It seems to only cater for query as a string type and the additional requestOptions

How would we structure this query?

**Comment by Baroshem** [comment]
Hey hey,

So basiaclly, requestOptions in useSearch composable accept both searchParams (query params) and the requestOptions. 

So you can do something like this:

```ts
await search({ query: 'Samsung', requestOptions: { hitsPerPage: 2 } })
```

The naming might not be perfect as algoliasearch also uses one object for options (also named requestOptions). For some reason, in the documentation it is described as two separate parameters but if you take a look at the algoliasearch.search completion, you will see that its the same as in the composable 

![image](https://user-images.githubusercontent.com/37120330/155952078-7420cbf6-550a-4e20-96de-96662eab74a7.png)


Maybe the better name could be just options, or actually dividing the requestOptions object into two separate objects.

However, at this point I would prefer to maintain consistency with the official algoliasearch docs and avoid unintentional breaking changes.

**Comment by andyjamesn** [comment]
Thanks for the clarification and yes I understand the complexity of naming here. This works perfectly!

I have tested it with filters too.

eg

```
await indexSearch({
    query: '',
    requestOptions: {
        filters: 'category:"features"'
    }
});
```

**Comment by Baroshem** [comment]
Wonderful,

I will close the question then. It can be reopened if needed and in case of other questions, feel free to post them here :)
