### ISSUE TITLE
DocSearch feature

### ISSUE THREAD

**Issue by Tahul** [nuxt-community/algolia-module#41]
### Is your feature request related to a problem? Please describe.

Hey 😄

I'm working on using Algolia DocSearch on Nuxt 3 new documentation website.

I've been trying to implement the feature using your module, but it seem like this feature from Algolia is not supported.

Here is the Pull Request I'm working on: https://github.com/nuxt/nuxt3-docs/pull/15

### Describe the solution you'd like

I've imported a component that we use since a while on docs project, and updated it to Composition API.

The component imports Algolia configuration from publicRuntimeConfig, which is close to what you do in this module.

We could work on having a toggleable parameter that would push a built-in component that is easy to use and take its configuration from nuxt.config.

### Additional context

Algolia DocSearch is a documentation search solution made for open source projects.

It ships with an easy component and scripts that let you build indexes from your project pages.

https://docsearch.algolia.com

**Comment by Baroshem** [comment]
Hey!

Thanks for creating this issue (and a WIP pull request)!

I will happily review it tomorrow. It seems like a really useful feature that many project could benefit from. I will be glad to help you with that and give you some hints/help developing.
