### ISSUE TITLE
vue instantsearch does not work with the rc version

### ISSUE THREAD

**Issue by Baroshem** [nuxt-community/algolia-module#49]
This is really strange because it works perfect on playground but when we tested it with Tim it was not working

**Comment by andyjamesn** [comment]
I used the base demo Stackblitz and added instantSearch to test and it is not working

Here is the Stackblitz

https://stackblitz.com/edit/github-rt1jxz-wcpzz5

The main change is the app.vue is setup based on the docs to use instantsearch and I ran

`npm install vue-instantsearch algoliasearch instantsearch.css`

I am not 100% sure if all that is needed but looking at the package json of the playground these are there so just to be sure I added them.

**Comment by Baroshem** [comment]
Hey, thanks for checking that out. I alse figured out the same results but did not write it down. This is strange however because previously (in earlier versions of the module) you were able to use the components without importing them. This is not a big issue as it can be sone manually but makes the DX a bit worse (but also better for performance because we are not auto importing everything)

**Comment by Baroshem** [comment]
Fixed with 0.9.2
