### ISSUE TITLE
Problem using search() outside of onMounted() hook

### ISSUE THREAD

**Issue by dmitryT93** [nuxt-community/algolia-module#60]
Have a problem displaying SSR data 
if i use code from example
```
<script setup>
const { result, search } = useSearch('test_index') // pass your index name as param

onMounted(async () => {
  await search({ query: 'Samsung' });
})
</script>
```
all work well, but data loaded after page load, but I would like to receive data before the page is fully loaded

if i try something like this
```
<script setup>
const { result, search } = useSearch('test_index') // pass your index name as param
await search({ query: 'Samsung' });
</script>
```

i catch **500** error,
text: **XMLHttpRequest is not defined**

```
"nuxt": "3.0.0-rc.1",
"@nuxtjs/algolia": "^0.9.2",
```

How could I solve this problem?
Thanks for the answer

**Comment by Baroshem** [comment]
Hey @dmitryT93 

This module does not yet support the SSR execution, but we are already working on it. You can follow #46 to get more details.

I will try to work on it as well this week to make it ready for the new release :)

**Comment by Baroshem** [comment]
I will close this issue in favor of #63
