### ISSUE TITLE
@nuxtjs/algolia: 1.0.0 Does not work with latest nuxt: 3.0.0-rc.4

### ISSUE THREAD

**Issue by jyotirmaybarman** [nuxt-community/algolia-module#70]
### Version

@nuxtjs/algolia: 1.0.0
nuxt: 3.0.0-rc.4

### Reproduction Link
https://stackblitz.com/edit/nuxt-starter-zh6pvp?file=package.json

### Steps to reproduce
Add api key & id
### What is Expected?
Expected to be working properly.
### What is actually happening?
Showing this error. It is working with `@nuxtjs/algolia:0.9.2` but the crawler is not indexing the content. (nuxt content v2)

![image](https://user-images.githubusercontent.com/56916274/177701834-74f07f91-6539-4e39-bdc9-7d062b0170fc.png)

**Comment by Baroshem** [comment]
Hey @jyotirmaybarman 

Thanks for reporting this issue. I will take a look at it :)

**Comment by Baroshem** [comment]
The issue was caused by the CMS indexer options failing to convert to object when not defined. 

It is working on 1.0.1 version. Try it out as I released it few minutes age :)
