### ISSUE TITLE
Module @nuxtjs/algolia is disabled due to incompatibility issues

### ISSUE THREAD

**Issue by marcusarnfast** [nuxt-community/algolia-module#90]
### Version

@nuxtjs/algolia: 1.1.1
nuxt: 3.0.0-r.c.9

### Reproduction Link

https://github.com/marcusarnfast/Incompatibility-issues-with-Algolia

### Steps to reproduce

Yarn add 

### What is Expected?

Algolia module to work

### What is actually happening?

Module @nuxtjs/algolia is disabled due to incompatibility issues:                                                                                                                                                   
 - [nuxt] Nuxt version `^3.0.0 || ^2.16.0` is required but currently using `3.0.0-rc.9`

**Comment by Baroshem** [comment]
Hey @marcusarnfast 

Thanks for reporting this issue. I am currently on holidays without access to the computer. I will work on this issue after I will be back (end of semptember).

In the meantime, you can edit the version in the node_modules/@nuxtjs/algolia/module.mjs (I think this is the right path) and change the compatibility. It is not perfect but should work.

**Comment by marcusarnfast** [comment]
I tried to do the qucikfix in the node_module, but "addImportsDir" is depreciated and when I change to "importsDir" I get no result from the Algolia module.. :-)

**Comment by marcusarnfast** [comment]
> 
Sorry this worked.. I just switched up the API_KEY and APP_ID

The quick fix for this issue is to add the "-rc" in node_modules\@nuxtjs\algolia\dist\module.mjs.

And then change autoImports:dirs to imports:dirs.

:-)

**Comment by Baroshem** [comment]
I am glad that it worked. 

I will update the module accordingly to the changes in the recent version of nuxt 3.
