### ISSUE TITLE
Fail on Nuxt 3 RC9

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt-community/algolia-module#91]
### Version

@nuxtjs/algolia: 1.1.0
nuxt: 3.0.0-rc.9

### Reproduction Link

We have updated Nuxt to version 3 RC 9 and it has thrown us an error. Please update module to work with RC 9

**Comment by agracia-foticos** [comment]
Fails the call to const { result, search } = useAlgoliaSearch('XXXXXX')

**Comment by Baroshem** [comment]
Hey @agracia-foticos 

I am currently on holidays without access to the computer so I wont be able to release a new version with a fix. I will do that later in september when I will be back.

Also, could you please paste the error here with more descriptive info?

**Comment by Lexpeartha** [comment]
@Baroshem there was a breaking change introduced in nuxt rc 9, check out nuxt/framework#7116

**Comment by ricky11** [comment]
This the error from vite : 
 WARN  Module FormKit is disabled due to incompatibility issues:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          11:00:41
 - [nuxt] Nuxt version `^3.0.0` is required but currently using `3.0.0-rc.9`

**Comment by podlebar** [comment]
i deploy to Vercel and this is what i get:
```ERROR	[nuxt] [request error] [unhandled] [500] Directory import '/var/task/node_modules/vue-instantsearch/vue3/es' is not supported resolving ES modules imported from /var/task/chunks/app/server.mjs```

i assume it's because of this: 
```
autoImports:dirs hook is deprecated. Use addImportsDir() from @nuxt/kit or imports:dirs with nuxt>=3.0.0-rc.9.
```

**Comment by Baroshem** [comment]
Guys, thanks for explaining the issue. It seems that the nuxt core team released a breaking change in the nuxt kit. The fix should be relatively simple (replacing the hook) but I wont be able to release a fix version with it as I am currently on holidays. I will be back end of september and then I will release the new version to fix your issues.

**Comment by monkemedia** [comment]
Does anyone have a quick fix for this in the meantime?

**Comment by lukaszflorczak** [comment]
Here is my patch. You can use [patch-package](https://www.npmjs.com/package/patch-package) and add the code below to `patches/@nuxtjs+algolia+1.1.1.patch` file. It works for me.

```diff
diff --git a/node_modules/@nuxtjs/algolia/dist/module.json b/node_modules/@nuxtjs/algolia/dist/module.json
index 506aa8c..7b327a0 100644
--- a/node_modules/@nuxtjs/algolia/dist/module.json
+++ b/node_modules/@nuxtjs/algolia/dist/module.json
@@ -2,7 +2,7 @@
   "name": "@nuxtjs/algolia",
   "configKey": "algolia",
   "compatibility": {
-    "nuxt": "^3.0.0 || ^2.16.0",
+    "nuxt": "^3.0.0-rc.9 || ^2.16.0",
     "bridge": true
   },
   "version": "1.1.1"
diff --git a/node_modules/@nuxtjs/algolia/dist/module.mjs b/node_modules/@nuxtjs/algolia/dist/module.mjs
index e37b246..13aba7d 100644
--- a/node_modules/@nuxtjs/algolia/dist/module.mjs
+++ b/node_modules/@nuxtjs/algolia/dist/module.mjs
@@ -90,7 +90,7 @@ const module = defineNuxtModule({
     name: "@nuxtjs/algolia",
     configKey: "algolia",
     compatibility: {
-      nuxt: "^3.0.0 || ^2.16.0",
+      nuxt: "^3.0.0-rc.9 || ^2.16.0",
       bridge: true
     }
   },
```

**Comment by monkemedia** [comment]
@lukaszflorczak Once I make these changes, do I do anything else? I just re-ran `npx nuxi dev` and am getting the following error: `Cannot destructure property 'applicationId' of '__vite_ssr_import_0__.useRuntimeConfig(...).algolia' as it is undefined.`

**Comment by lukaszflorczak** [comment]
@monkemedia
1. Complete the `Set-up` section: https://github.com/ds300/patch-package#set-up. You have to add `postinstall` in your `package.json` and of course install `patch-package`. 
2. Run again `npm/yarn/pnpm install` – the patch will be automatically applied after installation.

**Comment by monkemedia** [comment]
@lukaszflorczak thank you for the instructions. I have never used patch package before. Seem to have done everything correctly and the patch has been installed, however, I am still getting the same error `Cannot destructure property 'applicationId'`

**Comment by monkemedia** [comment]
Fixed it by following this https://github.com/nuxt-community/algolia-module/issues/84

**Comment by Baroshem** [comment]
Guys, the new version has been released. You can verify now if it works correctly. I have tested it in several nuxt projects and it is working correctly :)

**Comment by lukaszflorczak** [comment]
In my project, everything works fine. Thank you!

**Comment by podlebar** [comment]
works with rc9 to rc11.
i upgraded my project step by step and i had no issues.

**Comment by Baroshem** [comment]
Closing the issue then. Thanks for the input guys!
